#ifndef ARBITER_HANDLER_ENUM_H
#define ARBITER_HANDLER_ENUM_H

#include "../TypeDefs.h"

enum EIOOpcodes : UINT16 {
	IO_REMOVE_PLAYER = 1,
	IO_LOAD_TOPO_FIN,
	IO_CHAT,
	IO_EXTERNAL_CHANGE,
	IO_SOCIAL,
	IO_SOCIAL_CANCEL,
	IO_RETURN_TO_LOBBY,
	IO_APPLY_TITLE,
	IO_SOCIAL_CHAT,
	IO_BROADCAST,

	IO_MAX
};

#endif