#ifndef CHATENUMS_H
#define CHATENUMS_H

#include "../TypeDefs.h"

enum EChatType : UINT16 {
	MAIN_CHAT = 0,
	PARTY_CHAT, // 1
	GUILD_CHAT, // 2
	SHAUT_CHAT, // zone
	TRADE_CHAT, // 4
	RAID_CHAT, // common raid
	CLUB_CHAT, // 6
	PRIVATE_CHAT, // 7
	WHISHPER_CHAT, // 8
	GREATING_CHAT, // 9
	UNK_1_CHAT, // 10
	CANAL_1_CHAT, // 11
	CANAL_2_CHAT, // 12
	CANAL_3_CHAT, // 13
	CANAL_4_CHAT, // 14
	CANAL_5_CHAT, // 15
	CANAL_6_CHAT, // 16
	CANAL_7_CHAT, // 17
	CANAL_8_CHAT, // 18
	TRADER_CHAT, // 19
	LFP_CHAT, // Looking for Party
	NOTICE_CHAT, // 21
	ADMIN_CHAT, // 22
	UNK_2_CHAT, // 23
	SYSTEM_CHAT, // 24
	RAID_LEADER_CHAT, // 25
	UNK_3, // 26
	GLOBAL_CHAT, // 27
	ALLIANCE_CHAT, // 28
	ECHELON_CHAT, // 29
	EXARCH_CHAT, // 30
	MEGAPHONE = 213,
	GUILD_ADVERTISMENTS = 214,

};


#endif
