#ifndef SERVER_DEFS_H
#define SERVER_DEFS_H

#define PPCAT_NX(A, B) A ## B
#define STRINGIZE(A) #A

#define TERA_SERVER_PORT 10001 
#define ARBITER_WORKERS_COUNT 2

#define MAX_CONNECTIONS 8192 
#define NAME_MAX 128
#define CONTINENT_NAME_MAX 128

#define IOCP_SERVER_SHUTDOWN_SANTINELL 1

#define PLAYER_DETAILS_1_BUFFER_SIZE  32
#define PLAYER_DETAILS_2_BUFFER_SIZE  64
#define PLAYER_DETAILS_3_BUFFER_SIZE  8
#define PLAYER_START_ITEMS_MAX  64
#define PLAYER_NAME_MAX_LENGTH  40

#define CONNECTION_RECV_BUFFER_LEN 2048


#define BIND_FAILED_MESSAGE STRINGIZE(STRINGIZE("Failed to bind to ", TERA_SERVER_PORT), "\n")
#endif
